### ISSUE TITLE
Spray Not Showing

### ISSUE THREAD

**Issue by scottjsh** [VALTracker/DesktopClient#13]
![image](https://user-images.githubusercontent.com/62782800/192142827-dc29e3cb-2adb-4e69-b17a-556a93b6f320.png)
![image](https://user-images.githubusercontent.com/62782800/192142848-a7f71fc9-ae7f-4902-be4a-9f88010f513b.png)

**Comment by SpiritLetsPlays** [comment]
Thanks for reporting this! 👍 
This issue has been fixed with **[Update v1.4.3](https://github.com/VALTracker/DesktopClient/releases/tag/v1.4.3)**.
